package com.honeypot.honeypot.entity;
// default package
// Generated 2015-10-13 16:33:40 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Warning generated by hbm2java
 */
public class Warning {

	private Integer id;
	private String warnContent;
	private Date warnTime;
	private String macAddress;
	private Integer flag;
	private String esId;

	public Warning() {
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getWarnContent() {
		return warnContent;
	}

	public void setWarnContent(String warnContent) {
		this.warnContent = warnContent;
	}

	public Date getWarnTime() {
		return warnTime;
	}

	public void setWarnTime(Date warnTime) {
		this.warnTime = warnTime;
	}

	public String getMacAddress() {
		return macAddress;
	}

	public void setMacAddress(String macAddress) {
		this.macAddress = macAddress;
	}

	public Integer getFlag() {
		return flag;
	}

	public void setFlag(Integer flag) {
		this.flag = flag;
	}

	public String getEsId() {
		return esId;
	}

	public void setEsId(String esId) {
		this.esId = esId;
	}

	public Warning(Integer id, String warnContent, Date warnTime,
			String macAddress, Integer flag) {
		super();
		this.id = id;
		this.warnContent = warnContent;
		this.warnTime = warnTime;
		this.macAddress = macAddress;
		this.flag = flag;
	}
	
}
