package com.honeypot.honeypot.entity;

import java.text.SimpleDateFormat;
// default package
// Generated 2015-10-13 16:33:40 by Hibernate Tools 3.4.0.CR1


/**
 * Warning generated by hbm2java
 */
public class WarningCriterial implements java.io.Serializable {

	private Integer id;
	private String warnContent;
	private String warnTime;
	private String macAddress;
	private String logType;
	private String esId;

	public WarningCriterial() {
	}

	public WarningCriterial(Integer id, String warnContent, String warnTime,
			String macAddress, String logType, String esId) {
		super();
		this.id = id;
		this.warnContent = warnContent;
		this.warnTime = warnTime;
		this.macAddress = macAddress;
		this.logType = logType;
		this.esId = esId;
	}
	
	public WarningCriterial(Warning w){
		this.id = w.getId();
		this.warnContent = w.getWarnContent();
		SimpleDateFormat df=new SimpleDateFormat("yyyy-MM-dd HH:MM:ss");
		this.warnTime = df.format(w.getWarnTime());
		this.macAddress = w.getMacAddress();
		switch (w.getFlag()) {
		case 1:
			this.logType = "sensitive";
			break;
		case 0:
			this.logType = "BA";
			break;
		case 2:
			this.logType = "virtual";
			break;
		default:
			break;
		}
		this.esId = w.getEsId();
	}


	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getWarnContent() {
		return this.warnContent;
	}

	public void setWarnContent(String warnContent) {
		this.warnContent = warnContent;
	}

	public String getWarnTime() {
		return this.warnTime;
	}

	public void setWarnTime(String warnTime) {
		this.warnTime = warnTime;
	}

	public String getMacAddress() {
		return macAddress;
	}

	public void setMacAddress(String macAddress) {
		this.macAddress = macAddress;
	}

	public String getLogType() {
		return logType;
	}

	public void setLogType(String logType) {
		this.logType = logType;
	}

	public String getEsId() {
		return esId;
	}

	public void setEsId(String esId) {
		this.esId = esId;
	}
	
	
	

}
